// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalGrupoAlyne.Data;

#nullable disable

namespace PortalGrupoAlyne.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230214141806_alteracaoParceiros")]
    partial class alteracaoParceiros
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortalGrupoAlyne.Model.Concorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Concorrente");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Indústria"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Distribuidora"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.GrupoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("GrupoProduto");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.GrupoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("GrupoUsuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Administrativo"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.ItemTabela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProd")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TabelaPrecoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProd");

                    b.HasIndex("TabelaPrecoId");

                    b.ToTable("ItemTabela");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 1,
                            Icon = "fa fa-bank",
                            Nome = "Administrativo",
                            Ordem = 0
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.MenuPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MenuPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("SubMenuId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("SubMenuId");

                    b.ToTable("Pagina");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 13,
                            Icon = "fa fa-briefcase",
                            MenuId = 1,
                            Nome = "Empresas",
                            SubMenuId = 1,
                            Url = "/cadastro-tipo-empresa"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 13,
                            Icon = "fa fa-user-plus",
                            MenuId = 1,
                            Nome = "Vendedores",
                            SubMenuId = 1,
                            Url = "/cadastro-vendedores"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 18,
                            Icon = "fa fa-credit-card",
                            MenuId = 1,
                            Nome = "Tipo de Negociação",
                            SubMenuId = 1,
                            Url = "/cadastro-tipo-negociacao"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 14,
                            Icon = "fa fa-users",
                            MenuId = 1,
                            Nome = "Parceiros",
                            SubMenuId = 1,
                            Url = "/cadastro-parceiros"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = 12,
                            Icon = "fa fa-shopping-bag",
                            MenuId = 1,
                            Nome = "Grupo de Produtos",
                            SubMenuId = 1,
                            Url = "/cadastro-grupos-produtos"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = 11,
                            Icon = "fa fa-cart-plus",
                            MenuId = 1,
                            Nome = "Produtos",
                            SubMenuId = 1,
                            Url = "/cadastro-produtos"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = 16,
                            Icon = "fa fa-user-times",
                            MenuId = 1,
                            Nome = "Concorrentes",
                            SubMenuId = 1,
                            Url = "/cadastro-concorrentes"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = 17,
                            Icon = "fa fa-user-times",
                            MenuId = 1,
                            Nome = "Produto x Concorrente",
                            SubMenuId = 1,
                            Url = "/produtos-concorrentes"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = 19,
                            Icon = "fa fa-calculator",
                            MenuId = 1,
                            Nome = "Tabela de Preço",
                            SubMenuId = 1,
                            Url = "/tabela-de-preco"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = 23,
                            Icon = "fa fa-line-chart",
                            MenuId = 1,
                            Nome = "Pedido de Vendas",
                            SubMenuId = 2,
                            Url = "/pedido_vendas"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = 9,
                            Icon = "fa fa-user-circle-o",
                            MenuId = 1,
                            Nome = "Usuarios",
                            SubMenuId = 4,
                            Url = "/cadastro-usuarios"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = 10,
                            Icon = "fa fa-users",
                            MenuId = 1,
                            Nome = "Grupo de Usuarios",
                            SubMenuId = 4,
                            Url = "/cadastro-grupo-usuarios"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = 22,
                            Icon = "fa fa-newspaper-o",
                            MenuId = 1,
                            Nome = "Montar Menu",
                            SubMenuId = 4,
                            Url = "/montar-menu"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = 21,
                            Icon = "fa fa-id-card-o",
                            MenuId = 1,
                            Nome = "Cadastro de Páginas",
                            SubMenuId = 4,
                            Url = "/cadastro-de-paginas"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.PaginaBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Url")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("PaginaBase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 1,
                            Icon = "fa fa-bank",
                            Nome = "Administrativo",
                            Url = ""
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 2,
                            Icon = "fa fa-bar-chart",
                            Nome = "Trade",
                            Url = ""
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 3,
                            Icon = "fa fa-money",
                            Nome = "Vendas",
                            Url = ""
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 4,
                            Icon = "fa fa-address-card",
                            Nome = "Cadastros",
                            Url = ""
                        },
                        new
                        {
                            Id = 5,
                            Codigo = 5,
                            Icon = "fa fa-map-o",
                            Nome = "Movimentos",
                            Url = ""
                        },
                        new
                        {
                            Id = 6,
                            Codigo = 6,
                            Icon = "fa fa-object-ungroup",
                            Nome = "Outros",
                            Url = ""
                        },
                        new
                        {
                            Id = 7,
                            Codigo = 7,
                            Icon = "fa fa-search-minus",
                            Nome = "Consultas",
                            Url = ""
                        },
                        new
                        {
                            Id = 8,
                            Codigo = 8,
                            Icon = "fa fa-file-o",
                            Nome = "Relatorios",
                            Url = ""
                        },
                        new
                        {
                            Id = 9,
                            Codigo = 9,
                            Icon = "fa fa-user-circle-o",
                            Nome = "Usuarios",
                            Url = "/cadastro-usuarios"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = 10,
                            Icon = "fa fa-users",
                            Nome = "Grupo de Usuarios",
                            Url = "/cadastro-grupo-usuarios"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = 11,
                            Icon = "fa fa-cart-plus",
                            Nome = "Produtos",
                            Url = "/cadastro-produtos"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = 12,
                            Icon = "fa fa-shopping-bag",
                            Nome = "Grupo de Produtos",
                            Url = "/cadastro-grupos-produtos"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = 13,
                            Icon = "fa fa-user-plus",
                            Nome = "Vendedores",
                            Url = "/cadastro-vendedores"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = 14,
                            Icon = "fa fa-users",
                            Nome = "Parceiros",
                            Url = "/cadastro-parceiros"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = 15,
                            Icon = "fa fa-briefcase",
                            Nome = "Empresas",
                            Url = "/cadastro-tipo-empresa"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = 16,
                            Icon = "fa fa-user-times",
                            Nome = "Concorrentes",
                            Url = "/cadastro-concorrentes"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = 17,
                            Icon = "fa fa-user-times",
                            Nome = "Produto x Concorrente",
                            Url = "/produtos-concorrentes"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = 18,
                            Icon = "fa fa-credit-card",
                            Nome = "Tipo de Negociação",
                            Url = "/cadastro-tipo-negociacao"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = 19,
                            Icon = "fa fa-calculator",
                            Nome = "Tabela de Preço",
                            Url = "/tabela-de-preco"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = 21,
                            Icon = "fa fa-id-card-o",
                            Nome = "Cadastro de Páginas",
                            Url = "/cadastro-de-paginas"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = 22,
                            Icon = "fa fa-newspaper-o",
                            Nome = "Montar Menu",
                            Url = "/montar-menu"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = 23,
                            Icon = "fa fa-line-chart",
                            Nome = "Pedido de Vendas",
                            Url = "/pedido_vendas"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.PaginaPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoUsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("MenuPermissaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("SubMenuPermissaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoUsuarioId");

                    b.HasIndex("MenuPermissaoId");

                    b.HasIndex("SubMenuPermissaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PaginaPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Parceiro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Canal")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Classificacao")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Cnpj_Cpf")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fone")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Lat")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Long")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PrimeiraSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Quarta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("QuartaSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Quinta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("QuintaSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Sabado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Segunda")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SegundaSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SemVisita")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Sexta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TamanhoLoja")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<bool>("Terca")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TerceiraSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoNegociacao")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoPessoa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UF")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int?>("codParceiro")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Parceiro");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GrupoProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoProdutoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.ProdutoConcorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CodConcorrente")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodProduto")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodProdutoConcorrente")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomeConcorrente")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeProduto")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeProdutoSimilar")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoConcorrente");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("SubMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 4,
                            Icon = "fa fa-address-card",
                            MenuId = 1,
                            Nome = "Cadastros",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 5,
                            Icon = "fa fa-map-o",
                            MenuId = 1,
                            Nome = "Movimentos",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 7,
                            Icon = "fa fa-search-minus",
                            MenuId = 1,
                            Nome = "Consultas",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 6,
                            Icon = "fa fa-object-ungroup",
                            MenuId = 1,
                            Nome = "Outros",
                            Ordem = 0
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenuPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("MenuPermissaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoUsuarioId");

                    b.HasIndex("MenuPermissaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SubMenuPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("TabelaPreco");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPrecoCliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CodEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("CodParceiro")
                        .HasColumnType("int");

                    b.Property<int>("CodTabelaPreco")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CodParceiro");

                    b.HasIndex("CodTabelaPreco");

                    b.ToTable("TabelaPrecoCliente");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPrecoParceiro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("ParceiroId")
                        .HasColumnType("int");

                    b.Property<int>("TabelaPrecoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ParceiroId");

                    b.HasIndex("TabelaPrecoId");

                    b.ToTable("TabelaPrecoParceiro");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TipoNegociacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("TipoNegociacao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Funcao")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemURL")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool?>("PrimeiroLoginAdm")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nfe@grupoalyne.com.br",
                            Funcao = "Administrador do Sistema",
                            GrupoId = 1,
                            ImagemURL = "",
                            NomeCompleto = "Administrador Grupo Alyne",
                            PasswordHash = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            PasswordSalt = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            PrimeiroLoginAdm = true,
                            RefreshToken = "",
                            Status = "1",
                            Telefone = "(85) 3521-8888",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AtuaCompras")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Regiao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.ItemTabela", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Produto", "Produtos")
                        .WithMany()
                        .HasForeignKey("IdProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.TabelaPreco", null)
                        .WithMany("ItemTabela")
                        .HasForeignKey("TabelaPrecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.MenuPermissao", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoUsuario", null)
                        .WithMany("MenuPermissao")
                        .HasForeignKey("GrupoUsuarioId");

                    b.HasOne("PortalGrupoAlyne.Model.Usuario", null)
                        .WithMany("MenuPermissao")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Pagina", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Menu", null)
                        .WithMany("Pagina")
                        .HasForeignKey("MenuId");

                    b.HasOne("PortalGrupoAlyne.Model.SubMenu", null)
                        .WithMany("Pagina")
                        .HasForeignKey("SubMenuId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.PaginaPermissao", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoUsuario", null)
                        .WithMany("PaginaPermissao")
                        .HasForeignKey("GrupoUsuarioId");

                    b.HasOne("PortalGrupoAlyne.Model.MenuPermissao", null)
                        .WithMany("PaginaPermissao")
                        .HasForeignKey("MenuPermissaoId");

                    b.HasOne("PortalGrupoAlyne.Model.SubMenuPermissao", null)
                        .WithMany("PaginaPermissao")
                        .HasForeignKey("SubMenuPermissaoId");

                    b.HasOne("PortalGrupoAlyne.Model.Usuario", null)
                        .WithMany("PaginaPermissao")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Parceiro", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Produto", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoProduto", "GrupoProduto")
                        .WithMany()
                        .HasForeignKey("GrupoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoProduto");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenu", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Menu", null)
                        .WithMany("SubMenu")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenuPermissao", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoUsuario", null)
                        .WithMany("SubMenuPermissao")
                        .HasForeignKey("GrupoUsuarioId");

                    b.HasOne("PortalGrupoAlyne.Model.MenuPermissao", null)
                        .WithMany("SubMenuPermissao")
                        .HasForeignKey("MenuPermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.Usuario", null)
                        .WithMany("SubMenuPermissao")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPrecoCliente", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Parceiro", "Parceiros")
                        .WithMany()
                        .HasForeignKey("CodParceiro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.TabelaPreco", "TabelaPreco")
                        .WithMany()
                        .HasForeignKey("CodTabelaPreco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parceiros");

                    b.Navigation("TabelaPreco");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPrecoParceiro", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.Parceiro", null)
                        .WithMany("TabelaPrecoParceiro")
                        .HasForeignKey("ParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.TabelaPreco", "TabelaPreco")
                        .WithMany()
                        .HasForeignKey("TabelaPrecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("TabelaPreco");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.GrupoUsuario", b =>
                {
                    b.Navigation("MenuPermissao");

                    b.Navigation("PaginaPermissao");

                    b.Navigation("SubMenuPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Menu", b =>
                {
                    b.Navigation("Pagina");

                    b.Navigation("SubMenu");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.MenuPermissao", b =>
                {
                    b.Navigation("PaginaPermissao");

                    b.Navigation("SubMenuPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Parceiro", b =>
                {
                    b.Navigation("TabelaPrecoParceiro");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenu", b =>
                {
                    b.Navigation("Pagina");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenuPermissao", b =>
                {
                    b.Navigation("PaginaPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPreco", b =>
                {
                    b.Navigation("ItemTabela");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Usuario", b =>
                {
                    b.Navigation("MenuPermissao");

                    b.Navigation("PaginaPermissao");

                    b.Navigation("SubMenuPermissao");
                });
#pragma warning restore 612, 618
        }
    }
}
