// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalGrupoAlyne.Data;

#nullable disable

namespace PortalGrupoAlyne.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortalGrupoAlyne.Model.CabecalhoPedidoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Baixado")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Filial")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Lote")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PalMPV")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<int>("ParceiroId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("TipoNegociacaoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<string>("pedido")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ParceiroId");

                    b.HasIndex("TipoNegociacaoId");

                    b.HasIndex("VendedorId");

                    b.ToTable("CabecalhoPedidoVenda");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Concorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Concorrente");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SankhyaSenha")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("SankhyaServidor")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("SankhyaUsuario")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Configuracao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SankhyaSenha = "SYNC550V",
                            SankhyaServidor = "http://10.0.0.254:8280/",
                            SankhyaUsuario = "ADMIN"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Industria"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Distribuidora"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.GrupoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("GrupoProduto");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.GrupoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("GrupoUsuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Administrativo"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.IntegracaoSankhya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChaveTabelaPortal")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("SqlObterSankhya")
                        .HasColumnType("longtext");

                    b.Property<string>("TabelaPortal")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("IntegracaoSankhya");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChaveTabelaPortal = "Id",
                            SqlObterSankhya = "SELECT CODVEND Id, APELIDO Nome, ATIVO Status, ISNULL(EMAIL, '') Email, \r\n                    TIPVEND Tipo, CASE WHEN ATUACOMPRADOR = 'S' THEN 1 ELSE 0 END AtuaCompras, DTALTER AtualizadoEm\r\n                    FROM TGFVEN VEN WHERE VEN.CODVEND = $VendedorId AND DTALTER > '$AtualizadoEm'",
                            TabelaPortal = "Vendedor"
                        },
                        new
                        {
                            Id = 2,
                            ChaveTabelaPortal = "Id",
                            SqlObterSankhya = "SELECT DISTINCT TPV.CODTIPVENDA Id, \r\n                        RTRIM(LTRIM(TPV.DESCRTIPVENDA)) Descricao,\r\n                        TPV.DHALTER AtualizadoEm\r\n                    FROM TGFTPV (NOLOCK) TPV\r\n                    JOIN TGFCPL (NOLOCK) CPL ON CPL.SUGTIPNEGSAID = TPV.CODTIPVENDA\r\n                    JOIN TGFPAR (NOLOCK) PAR ON PAR.CODPARC = CPL.CODPARC AND PAR.CLIENTE = 'S'\r\n                    JOIN TGFPAEM (NOLOCK) PAEM ON PAEM.CODPARC = PAR.CODPARC AND PAEM.CODEMP = 1		\r\n                    JOIN TGFVEN (NOLOCK) VEN ON VEN.CODVEND = PAR.CODVEND AND VEN.TIPVEND = 'R' \r\n                                            AND VEN.CODVEND = $VendedorId\r\n                    WHERE TPV.CODTIPVENDA > 0\r\n                    AND DHALTER > '$AtualizadoEm'\r\n                    ORDER BY 1",
                            TabelaPortal = "TipoNegociacao"
                        },
                        new
                        {
                            Id = 3,
                            ChaveTabelaPortal = "Id",
                            SqlObterSankhya = "SELECT PAR.CODPARC Id, REPLACE(PAR.RAZAOSOCIAL, CHAR(39),'') Nome, \r\n                        PAR.TIPPESSOA TipoPessoa, REPLACE(PAR.NOMEPARC, CHAR(39),'') NomeFantasia, \r\n                        PAR.CGC_CPF Cnpj_Cpf, ISNULL(PAR.EMAIL,'') Email, \r\n                        ISNULL(PAR.TELEFONE,'') Fone, PAR.CODTIPPARC Canal, \r\n                        REPLACE(ISNULL(EN1.TIPO +' '+ EN1.NOMEEND,''), CHAR(39), '') Endereco,\r\n                        REPLACE(ISNULL(BAI.NOMEBAI,''), CHAR(39),'') Bairro,\r\n                        REPLACE(CID.NOMECID, CHAR(39),'') Municipio, UFS.UF UF, \r\n                        PAR.ATIVO Status, ISNULL(CPL.SUGTIPNEGSAID,0) TipoNegociacao, \r\n                        PAR.CODVEND VendedorId, PAR.DTALTER AtualizadoEm\r\n                        , ISNULL(PAR.LIMCRED,0) as LC\r\n                    FROM TGFPAR (NOLOCK) PAR\r\n					JOIN TGFVEN (NOLOCK) VEN ON VEN.CODVEND = PAR.CODVEND AND VEN.TIPVEND = 'R' \r\n                                            AND VEN.CODVEND = $VendedorId\r\n                    JOIN TSICID (NOLOCK) CID ON CID.CODCID = PAR.CODCID\r\n                    JOIN TSIUFS (NOLOCK) UFS ON UFS.CODUF = CID.UF\r\n                    LEFT JOIN TGFCPL (NOLOCK) CPL ON CPL.CODPARC = PAR.CODPARC\r\n                    LEFT JOIN TSIEND (NOLOCK) EN1 ON EN1.CODEND = PAR.CODEND\r\n                    LEFT JOIN TSIBAI (NOLOCK) BAI ON BAI.CODBAI = PAR.CODBAI\r\n                    WHERE PAR.CLIENTE = 'S' \r\n                    AND PAR.CODPARC > 0 \r\n                    AND PAR.CODVEND > 0\r\n                    AND PAR.ATIVO = 'S'",
                            TabelaPortal = "Parceiro"
                        },
                        new
                        {
                            Id = 4,
                            ChaveTabelaPortal = "Id",
                            SqlObterSankhya = "SELECT convert(int,SUBSTRING(RTRIM(CODGRUPOPROD),2,5)) Id, \r\n                    RTRIM(LTRIM(REPLACE(ISNULL(DESCRGRUPOPROD,''), CHAR(39),''))) Nome\r\n                    FROM sankhya.TGFGRU (NOLOCK)\r\n                    WHERE ANALITICO = 'S'\r\n                    and SUBSTRING(RTRIM(CODGRUPOPROD),1,3) = '120'",
                            TabelaPortal = "GrupoProduto"
                        },
                        new
                        {
                            Id = 5,
                            ChaveTabelaPortal = "Id",
                            SqlObterSankhya = "SELECT PRO.CODPROD Id, \r\n                        PRO.DESCRPROD Nome, \r\n                        convert(int,SUBSTRING(RTRIM(CODGRUPOPROD),2,5)) GrupoProdutoId,\r\n                        PRO.DTALTER AtualizadoEm,\r\n                        PRO.CODVOL TipoUnid,\r\n                        ISNULL(VOA.CODVOL,'UN') TipoUnid2,\r\n                        ISNULL(VOA.QUANTIDADE,1) Conv\r\n                    FROM sankhya.TGFPRO (NOLOCK) PRO\r\n                    LEFT JOIN sankhya.TGFVOA (NOLOCK) VOA ON VOA.CODPROD = PRO.CODPROD AND VOA.ATIVO = 'S' AND VOA.AD_UNCOM = 'S'\r\n                    LEFT JOIN sankhya.TGFIPI (NOLOCK) IPI ON IPI.CODIPI = PRO.CODIPI AND VOA.ATIVO = 'S'\r\n                    WHERE PRO.CODPROD <> 0 AND PRO.USOPROD IN ('V','R')\r\n                    AND PRO.DTALTER > '$AtualizadoEm'",
                            TabelaPortal = "Produto"
                        },
                        new
                        {
                            Id = 6,
                            ChaveTabelaPortal = "Id",
                            SqlObterSankhya = "SELECT NTA.CODTAB Id, 1 Codigo, RTRIM(LTRIM(NTA.NOMETAB)) Descricao, TAB.DTVIGOR DataInicial, '2070-01-01 01:01:01' DataFinal \r\n                    FROM TGFNTA (NOLOCK) NTA\r\n                    JOIN (SELECT CODTAB, MAX(DTVIGOR) DTVIGOR FROM TGFTAB (NOLOCK) GROUP BY CODTAB) TAB ON TAB.CODTAB = NTA.CODTAB\r\n                    JOIN TGFPAEM (NOLOCK) PAEM ON PAEM.CODTAB = NTA.CODTAB\r\n                    JOIN TGFPAR (NOLOCK) PAR ON PAR.CODPARC = PAEM.CODPARC\r\n                    JOIN TGFVEN (NOLOCK) VEN ON VEN.CODVEND = PAR.CODVEND \r\n                                            AND VEN.CODVEND = $VendedorId AND VEN.TIPVEND = 'R'\r\n                    GROUP BY NTA.CODTAB,TAB.CODTAB,RTRIM(LTRIM(NTA.NOMETAB)),TAB.DTVIGOR \r\n                    ORDER BY 1",
                            TabelaPortal = "TabelaPreco"
                        },
                        new
                        {
                            Id = 7,
                            ChaveTabelaPortal = "TabelaPrecoId,IdProd",
                            SqlObterSankhya = "SELECT TAB.CODTAB TabelaPrecoId, EXC.CODPROD IdProd, EXC.VLRVENDA Preco, \r\n                    ISNULL(EXC.AD_DTALTER, '1970-01-01 01:01:02') AtualizadoEm\r\n                    FROM TGFTAB TAB\r\n                    JOIN TGFNTA NTA ON NTA.CODTAB = TAB.CODTAB\r\n                    JOIN TGFEXC EXC ON EXC.NUTAB = TAB.NUTAB\r\n                    JOIN TGFPRO PRO ON PRO.CODPROD = EXC.CODPROD\r\n                    WHERE TAB.CODTAB IN (	SELECT NTA.CODTAB \r\n                                            FROM TGFNTA (NOLOCK) NTA\r\n                                            JOIN TGFPAEM (NOLOCK) PAEM ON PAEM.CODTAB = NTA.CODTAB\r\n                                            JOIN TGFPAR (NOLOCK) PAR ON PAR.CODPARC = PAEM.CODPARC\r\n						                    JOIN TGFVEN (NOLOCK) VEN ON VEN.CODVEND = PAR.CODVEND \r\n                                                                    AND VEN.CODVEND = $VendedorId AND VEN.TIPVEND = 'R' \r\n                                            GROUP BY NTA.CODTAB,RTRIM(LTRIM(NTA.NOMETAB)))\r\n                    AND EXC.NUTAB = (SELECT TOP 1 NUTAB FROM TGFTAB WHERE CODTAB = TAB.CODTAB\r\n                                    AND CONVERT(DATE,DTVIGOR) <= CONVERT(DATE,GETDATE())\r\n                                    ORDER BY EXC.CODPROD, DTVIGOR DESC)\r\n                    --AND ISNULL(EXC.AD_DTALTER, '1970-01-01 01:01:02') > '$AtualizadoEm'\r\n                    ORDER BY TAB.CODTAB, PRO.CODPROD",
                            TabelaPortal = "ItemTabela"
                        },
                        new
                        {
                            Id = 8,
                            ChaveTabelaPortal = "ParceiroId,EmpresaId,TabelaPrecoId",
                            SqlObterSankhya = "SELECT PAR.CODPARC ParceiroId, PAEM.CODEMP EmpresaId, PAEM.CODTAB TabelaPrecoId\r\n                    FROM TGFPAR (NOLOCK) PAR\r\n                    JOIN TGFPAEM (NOLOCK) PAEM ON PAEM.CODPARC = PAR.CODPARC\r\n                    JOIN TGFVEN (NOLOCK) VEN ON VEN.CODVEND = PAR.CODVEND\r\n                                            AND VEN.CODVEND = $VendedorId \r\n                                            AND VEN.TIPVEND = 'R'\r\n                    WHERE PAR.CLIENTE = 'S' \r\n                    AND PAR.CODPARC > 0 \r\n                    AND PAR.CODVEND > 0\r\n                    AND PAR.ATIVO = 'S'",
                            TabelaPortal = "TabelaPrecoParceiro"
                        },
                        new
                        {
                            Id = 9,
                            ChaveTabelaPortal = "EmpresaId,ParceiroId,NuUnico",
                            SqlObterSankhya = "SELECT FIN.CODEMP as EmpresaId\r\n	                , FIN.CODPARC as ParceiroId\r\n	                , FIN.NUNOTA as NuUnico\r\n	                , FIN.DESDOBRAMENTO as Parcela\r\n	                , CONVERT(DATE,FIN.DTNEG) as DataEmissao\r\n	                , CONVERT(DATE,FIN.DTVENC) as DataVencim\r\n	                , FIN.VLRDESDOB as Valor\r\n	\r\n	                FROM TGFFIN FIN \r\n	                JOIN TGFCAB CAB ON CAB.NUNOTA = FIN.NUNOTA\r\n	                WHERE (VLRDESDOB-(VLRBAIXA+VLRDESC)) > 0\r\n		                AND PROVISAO = 'N'\r\n		                AND FIN.RECDESP = 1\r\n		                AND FIN.DHBAIXA IS NULL\r\n		                AND FIN.CODTIPTIT IN (0,4)\r\n		                AND FIN.CODTIPOPER NOT IN (1020,5016,5019,5029)\r\n		                AND CONVERT(DATE,FIN.DTVENC) < convert(date,dateadd(day, -3, getdate()))\r\n		                AND FIN.CODVEND = $VendedorId \r\n		                AND FIN.CODPARC NOT IN (471,512,589,1293)",
                            TabelaPortal = "Titulo"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.ItemPedidoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Baixado")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("CabecalhoPedidoVendaId")
                        .HasColumnType("int");

                    b.Property<string>("Filial")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("PalMPV")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ValTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ValUnit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabecalhoPedidoVendaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendedorId");

                    b.ToTable("ItemPedidoVenda");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.ItemTabela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProd")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TabelaPrecoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProd");

                    b.HasIndex("TabelaPrecoId");

                    b.ToTable("ItemTabela");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 1,
                            Icon = "fa fa-bank",
                            Nome = "Administrativo",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 4,
                            Icon = "fa fa-address-card",
                            Nome = "Cadastros",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 5,
                            Icon = "fa fa-map-o",
                            Nome = "Movimentos",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 7,
                            Icon = "fa fa-search-minus",
                            Nome = "Consultas",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 5,
                            Codigo = 6,
                            Icon = "fa fa-object-ungroup",
                            Nome = "Outros",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 10,
                            Codigo = 25,
                            Icon = "fa fa-cogs",
                            Nome = "Configurações",
                            Ordem = 0
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.MenuPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MenuPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("SubMenuId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("SubMenuId");

                    b.ToTable("Pagina");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 13,
                            Icon = "fa fa-briefcase",
                            MenuId = 1,
                            Nome = "Empresas",
                            SubMenuId = 1,
                            Url = "/cadastro-tipo-empresa"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 13,
                            Icon = "fa fa-user-plus",
                            MenuId = 1,
                            Nome = "Vendedores",
                            SubMenuId = 1,
                            Url = "/cadastro-vendedores"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 18,
                            Icon = "fa fa-credit-card",
                            MenuId = 1,
                            Nome = "Tipo de Negociação",
                            SubMenuId = 1,
                            Url = "/cadastro-tipo-negociacao"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 14,
                            Icon = "fa fa-users",
                            MenuId = 1,
                            Nome = "Parceiros",
                            SubMenuId = 1,
                            Url = "/cadastro-parceiros"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = 12,
                            Icon = "fa fa-shopping-bag",
                            MenuId = 1,
                            Nome = "Grupo de Produtos",
                            SubMenuId = 1,
                            Url = "/cadastro-grupos-produtos"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = 11,
                            Icon = "fa fa-cart-plus",
                            MenuId = 1,
                            Nome = "Produtos",
                            SubMenuId = 1,
                            Url = "/cadastro-produtos"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = 16,
                            Icon = "fa fa-user-times",
                            MenuId = 1,
                            Nome = "Concorrentes",
                            SubMenuId = 1,
                            Url = "/cadastro-concorrentes"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = 17,
                            Icon = "fa fa-user-times",
                            MenuId = 1,
                            Nome = "Produto x Concorrente",
                            SubMenuId = 1,
                            Url = "/produtos-concorrentes"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = 19,
                            Icon = "fa fa-calculator",
                            MenuId = 1,
                            Nome = "Tabela de Preço",
                            SubMenuId = 1,
                            Url = "/tabela-de-preco"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = 23,
                            Icon = "fa fa-line-chart",
                            MenuId = 1,
                            Nome = "Pedido de Vendas",
                            SubMenuId = 2,
                            Url = "/pedido_vendas"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = 9,
                            Icon = "fa fa-user-circle-o",
                            MenuId = 1,
                            Nome = "Usuarios",
                            SubMenuId = 4,
                            Url = "/cadastro-usuarios"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = 10,
                            Icon = "fa fa-users",
                            MenuId = 1,
                            Nome = "Grupo de Usuarios",
                            SubMenuId = 4,
                            Url = "/cadastro-grupo-usuarios"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = 24,
                            Icon = "fa fa-external-link-square",
                            MenuId = 1,
                            Nome = "Receber dados Sankhya",
                            SubMenuId = 4,
                            Url = ""
                        },
                        new
                        {
                            Id = 29,
                            Codigo = 26,
                            Icon = "fa fa-refresh",
                            MenuId = 1,
                            Nome = "Restaurar dados sistema",
                            SubMenuId = 10,
                            Url = ""
                        },
                        new
                        {
                            Id = 17,
                            Codigo = 13,
                            Icon = "fa fa-briefcase",
                            MenuId = 2,
                            Nome = "Empresas",
                            Url = "/cadastro-tipo-empresa"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = 13,
                            Icon = "fa fa-user-plus",
                            MenuId = 2,
                            Nome = "Vendedores",
                            Url = "/cadastro-vendedores"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = 18,
                            Icon = "fa fa-credit-card",
                            MenuId = 2,
                            Nome = "Tipo de Negociação",
                            Url = "/cadastro-tipo-negociacao"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = 14,
                            Icon = "fa fa-users",
                            MenuId = 2,
                            Nome = "Parceiros",
                            Url = "/cadastro-parceiros"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = 12,
                            Icon = "fa fa-shopping-bag",
                            MenuId = 2,
                            Nome = "Grupo de Produtos",
                            Url = "/cadastro-grupos-produtos"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = 11,
                            Icon = "fa fa-cart-plus",
                            MenuId = 2,
                            Nome = "Produtos",
                            Url = "/cadastro-produtos"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = 16,
                            Icon = "fa fa-user-times",
                            MenuId = 2,
                            Nome = "Concorrentes",
                            Url = "/cadastro-concorrentes"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = 17,
                            Icon = "fa fa-user-times",
                            MenuId = 2,
                            Nome = "Produto x Concorrente",
                            Url = "/produtos-concorrentes"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = 19,
                            Icon = "fa fa-calculator",
                            MenuId = 2,
                            Nome = "Tabela de Preço",
                            Url = "/tabela-de-preco"
                        },
                        new
                        {
                            Id = 26,
                            Codigo = 23,
                            Icon = "fa fa-line-chart",
                            MenuId = 3,
                            Nome = "Pedido de Vendas",
                            Url = "/pedido_vendas"
                        },
                        new
                        {
                            Id = 27,
                            Codigo = 9,
                            Icon = "fa fa-user-circle-o",
                            MenuId = 5,
                            Nome = "Usuarios",
                            Url = "/cadastro-usuarios"
                        },
                        new
                        {
                            Id = 28,
                            Codigo = 10,
                            Icon = "fa fa-users",
                            MenuId = 5,
                            Nome = "Grupo de Usuarios",
                            Url = "/cadastro-grupo-usuarios"
                        },
                        new
                        {
                            Id = 31,
                            Codigo = 24,
                            Icon = "fa fa-external-link-square",
                            MenuId = 5,
                            Nome = "Receber dados Sankhya",
                            Url = ""
                        },
                        new
                        {
                            Id = 32,
                            Codigo = 26,
                            Icon = "fa fa-refresh",
                            MenuId = 10,
                            Nome = "Restaurar dados sistema",
                            Url = ""
                        },
                        new
                        {
                            Id = 33,
                            Codigo = 27,
                            Icon = "fa fa-line-chart",
                            MenuId = 3,
                            Nome = "Dashboard",
                            Url = "/dashboard"
                        },
                        new
                        {
                            Id = 34,
                            Codigo = 27,
                            Icon = "fa fa-line-chart",
                            MenuId = 1,
                            Nome = "Dashboard",
                            SubMenuId = 2,
                            Url = "/dashboard"
                        },
                        new
                        {
                            Id = 35,
                            Codigo = 28,
                            Icon = "fa fa-cogs",
                            MenuId = 1,
                            Nome = "Configurações Avançadas",
                            SubMenuId = 10,
                            Url = "/configuracoes"
                        },
                        new
                        {
                            Id = 36,
                            Codigo = 28,
                            Icon = "fa fa-cogs",
                            MenuId = 10,
                            Nome = "Configurações Avançadas",
                            Url = "/configuracoes"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.PaginaBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Url")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("PaginaBase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 1,
                            Icon = "fa fa-bank",
                            Nome = "Administrativo",
                            Url = ""
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 2,
                            Icon = "fa fa-bar-chart",
                            Nome = "Trade",
                            Url = ""
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 3,
                            Icon = "fa fa-money",
                            Nome = "Vendas",
                            Url = ""
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 4,
                            Icon = "fa fa-address-card",
                            Nome = "Cadastros",
                            Url = ""
                        },
                        new
                        {
                            Id = 5,
                            Codigo = 5,
                            Icon = "fa fa-map-o",
                            Nome = "Movimentos",
                            Url = ""
                        },
                        new
                        {
                            Id = 6,
                            Codigo = 6,
                            Icon = "fa fa-object-ungroup",
                            Nome = "Outros",
                            Url = ""
                        },
                        new
                        {
                            Id = 7,
                            Codigo = 7,
                            Icon = "fa fa-search-minus",
                            Nome = "Consultas",
                            Url = ""
                        },
                        new
                        {
                            Id = 8,
                            Codigo = 8,
                            Icon = "fa fa-file-o",
                            Nome = "Relatorios",
                            Url = ""
                        },
                        new
                        {
                            Id = 9,
                            Codigo = 9,
                            Icon = "fa fa-user-circle-o",
                            Nome = "Usuarios",
                            Url = "/cadastro-usuarios"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = 10,
                            Icon = "fa fa-users",
                            Nome = "Grupo de Usuarios",
                            Url = "/cadastro-grupo-usuarios"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = 11,
                            Icon = "fa fa-cart-plus",
                            Nome = "Produtos",
                            Url = "/cadastro-produtos"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = 12,
                            Icon = "fa fa-shopping-bag",
                            Nome = "Grupo de Produtos",
                            Url = "/cadastro-grupos-produtos"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = 13,
                            Icon = "fa fa-user-plus",
                            Nome = "Vendedores",
                            Url = "/cadastro-vendedores"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = 14,
                            Icon = "fa fa-users",
                            Nome = "Parceiros",
                            Url = "/cadastro-parceiros"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = 15,
                            Icon = "fa fa-briefcase",
                            Nome = "Empresas",
                            Url = "/cadastro-tipo-empresa"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = 16,
                            Icon = "fa fa-user-times",
                            Nome = "Concorrentes",
                            Url = "/cadastro-concorrentes"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = 17,
                            Icon = "fa fa-user-times",
                            Nome = "Produto x Concorrente",
                            Url = "/produtos-concorrentes"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = 18,
                            Icon = "fa fa-credit-card",
                            Nome = "Tipo de Negociação",
                            Url = "/cadastro-tipo-negociacao"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = 19,
                            Icon = "fa fa-calculator",
                            Nome = "Tabela de Preço",
                            Url = "/tabela-de-preco"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = 21,
                            Icon = "fa fa-id-card-o",
                            Nome = "Cadastro de Páginas",
                            Url = "/cadastro-de-paginas"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = 22,
                            Icon = "fa fa-newspaper-o",
                            Nome = "Montar Menu",
                            Url = "/montar-menu"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = 23,
                            Icon = "fa fa-line-chart",
                            Nome = "Pedido de Vendas",
                            Url = "/pedido_vendas"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = 24,
                            Icon = "fa fa-external-link-square",
                            Nome = "Receber dados Sankhya",
                            Url = ""
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.PaginaPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoUsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("MenuPermissaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("SubMenuPermissaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoUsuarioId");

                    b.HasIndex("MenuPermissaoId");

                    b.HasIndex("SubMenuPermissaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PaginaPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Parceiro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Canal")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Classificacao")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Cnpj_Cpf")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fone")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Lat")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Lc")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Long")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Municipio")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("PrimeiraSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Quarta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("QuartaSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Quinta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("QuintaSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Sabado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Segunda")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SegundaSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("SemVisita")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Sexta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TamanhoLoja")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<bool?>("Terca")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("TerceiraSem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoNegociacao")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoPessoa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UF")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int?>("codParceiro")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Parceiro");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Conv")
                        .HasColumnType("int");

                    b.Property<int>("GrupoProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("TipoUnid")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("TipoUnid2")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoProdutoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.ProdutoConcorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CodConcorrente")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodProduto")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodProdutoConcorrente")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomeConcorrente")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeProduto")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NomeProdutoSimilar")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoConcorrente");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("SubMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = 4,
                            Icon = "fa fa-address-card",
                            MenuId = 1,
                            Nome = "Cadastros",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 2,
                            Codigo = 5,
                            Icon = "fa fa-map-o",
                            MenuId = 1,
                            Nome = "Movimentos",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 3,
                            Codigo = 7,
                            Icon = "fa fa-search-minus",
                            MenuId = 1,
                            Nome = "Consultas",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 4,
                            Codigo = 6,
                            Icon = "fa fa-object-ungroup",
                            MenuId = 1,
                            Nome = "Outros",
                            Ordem = 0
                        },
                        new
                        {
                            Id = 10,
                            Codigo = 25,
                            Icon = "fa fa-cogs",
                            MenuId = 1,
                            Nome = "Configurações",
                            Ordem = 0
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenuPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("MenuPermissaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoUsuarioId");

                    b.HasIndex("MenuPermissaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SubMenuPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("TabelaPreco");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPrecoParceiro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("ParceiroId")
                        .HasColumnType("int");

                    b.Property<int>("TabelaPrecoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ParceiroId");

                    b.HasIndex("TabelaPrecoId");

                    b.ToTable("TabelaPrecoParceiro");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TipoNegociacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("TipoNegociacao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Titulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVencim")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int?>("NuUnico")
                        .HasColumnType("int");

                    b.Property<int?>("ParceiroId")
                        .HasColumnType("int");

                    b.Property<int?>("Parcela")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ParceiroId");

                    b.ToTable("Titulo");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Funcao")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemURL")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<bool?>("PrimeiroLoginAdm")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nfe@grupoalyne.com.br",
                            Funcao = "Administrador do Sistema",
                            GrupoId = 1,
                            ImagemURL = "",
                            NomeCompleto = "Administrador Grupo Alyne",
                            PasswordHash = new byte[] { 184, 32, 86, 255, 201, 2, 114, 128, 76, 107, 107, 81, 172, 115, 182, 212, 245, 152, 45, 245, 145, 163, 185, 172, 134, 122, 40, 217, 143, 159, 216, 223, 90, 8, 75, 157, 249, 106, 147, 40, 31, 211, 229, 86, 23, 90, 162, 188, 207, 36, 75, 190, 44, 199, 199, 218, 51, 90, 182, 108, 131, 58, 47, 175 },
                            PasswordSalt = new byte[] { 149, 117, 134, 111, 23, 78, 183, 149, 107, 251, 67, 190, 131, 242, 119, 119, 107, 80, 234, 32, 1, 36, 160, 106, 47, 142, 207, 146, 68, 92, 95, 239 },
                            PrimeiroLoginAdm = true,
                            RefreshToken = "",
                            Status = "1",
                            Telefone = "(85) 3521-8888",
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("AtuaCompras")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Regiao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.CabecalhoPedidoVenda", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Parceiro", "Parceiro")
                        .WithMany()
                        .HasForeignKey("ParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.TipoNegociacao", "TipoNegociacao")
                        .WithMany()
                        .HasForeignKey("TipoNegociacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parceiro");

                    b.Navigation("TipoNegociacao");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.ItemPedidoVenda", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.CabecalhoPedidoVenda", null)
                        .WithMany("ItemPedidoVenda")
                        .HasForeignKey("CabecalhoPedidoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.ItemTabela", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Produto", "Produtos")
                        .WithMany()
                        .HasForeignKey("IdProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.TabelaPreco", null)
                        .WithMany("ItemTabela")
                        .HasForeignKey("TabelaPrecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.MenuPermissao", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoUsuario", null)
                        .WithMany("MenuPermissao")
                        .HasForeignKey("GrupoUsuarioId");

                    b.HasOne("PortalGrupoAlyne.Model.Usuario", null)
                        .WithMany("MenuPermissao")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Pagina", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Menu", null)
                        .WithMany("Pagina")
                        .HasForeignKey("MenuId");

                    b.HasOne("PortalGrupoAlyne.Model.SubMenu", null)
                        .WithMany("Pagina")
                        .HasForeignKey("SubMenuId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.PaginaPermissao", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoUsuario", null)
                        .WithMany("PaginaPermissao")
                        .HasForeignKey("GrupoUsuarioId");

                    b.HasOne("PortalGrupoAlyne.Model.MenuPermissao", null)
                        .WithMany("PaginaPermissao")
                        .HasForeignKey("MenuPermissaoId");

                    b.HasOne("PortalGrupoAlyne.Model.SubMenuPermissao", null)
                        .WithMany("PaginaPermissao")
                        .HasForeignKey("SubMenuPermissaoId");

                    b.HasOne("PortalGrupoAlyne.Model.Usuario", null)
                        .WithMany("PaginaPermissao")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Parceiro", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Produto", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoProduto", "GrupoProduto")
                        .WithMany()
                        .HasForeignKey("GrupoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoProduto");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenu", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Menu", null)
                        .WithMany("SubMenu")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenuPermissao", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoUsuario", null)
                        .WithMany("SubMenuPermissao")
                        .HasForeignKey("GrupoUsuarioId");

                    b.HasOne("PortalGrupoAlyne.Model.MenuPermissao", null)
                        .WithMany("SubMenuPermissao")
                        .HasForeignKey("MenuPermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.Usuario", null)
                        .WithMany("SubMenuPermissao")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPrecoParceiro", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.Parceiro", null)
                        .WithMany("TabelaPrecoParceiro")
                        .HasForeignKey("ParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalGrupoAlyne.Model.TabelaPreco", "TabelaPreco")
                        .WithMany()
                        .HasForeignKey("TabelaPrecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("TabelaPreco");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Titulo", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.Parceiro", null)
                        .WithMany("Titulo")
                        .HasForeignKey("ParceiroId");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Usuario", b =>
                {
                    b.HasOne("PortalGrupoAlyne.Model.GrupoUsuario", "GrupoUsuario")
                        .WithMany()
                        .HasForeignKey("GrupoId");

                    b.Navigation("GrupoUsuario");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.CabecalhoPedidoVenda", b =>
                {
                    b.Navigation("ItemPedidoVenda");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.GrupoUsuario", b =>
                {
                    b.Navigation("MenuPermissao");

                    b.Navigation("PaginaPermissao");

                    b.Navigation("SubMenuPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Menu", b =>
                {
                    b.Navigation("Pagina");

                    b.Navigation("SubMenu");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.MenuPermissao", b =>
                {
                    b.Navigation("PaginaPermissao");

                    b.Navigation("SubMenuPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Parceiro", b =>
                {
                    b.Navigation("TabelaPrecoParceiro");

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenu", b =>
                {
                    b.Navigation("Pagina");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.SubMenuPermissao", b =>
                {
                    b.Navigation("PaginaPermissao");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.TabelaPreco", b =>
                {
                    b.Navigation("ItemTabela");
                });

            modelBuilder.Entity("PortalGrupoAlyne.Model.Usuario", b =>
                {
                    b.Navigation("MenuPermissao");

                    b.Navigation("PaginaPermissao");

                    b.Navigation("SubMenuPermissao");
                });
#pragma warning restore 612, 618
        }
    }
}
